version: "3.1"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: chaiaurcode
      MYSQL_DATABASE: database_development_1
      # remove MYSQL_USER=root (invalid)
      # optionally create a dev user if you want (uncomment below)
      # MYSQL_USER: chai
      # MYSQL_PASSWORD: chai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
